/* Flash Gallery — runtime configuration
 *
 * The one file you edit to change what the kiosk shows. No content lives in
 * app code; everything routes through the catalog source named here.
 *
 * SWITCHING FROM PLACEHOLDER TO REAL CONTENT
 * ------------------------------------------
 *   1. set `catalogSource: 'live'`
 *   2. fill in `live.url` (Supabase REST endpoint for the `kiosk_catalog`
 *      view) and `live.anonKey`
 *   3. delete `assets/seed/`, `seed/`, and the one `seed/seed-data.js`
 *      script tag in index.html
 *
 * That is the whole migration. No view code, no query code, and no markup
 * beyond that one tag knows the difference — the kiosk normalizes every
 * source into the same shape (see catalog.js).
 */
window.KIOSK_CONFIG = {

  /* 'seed' — placeholder content generated by tools/generate-seed.py
   * 'live' — Supabase-backed catalog
   * 'sheets-only' — force the legacy linear sheet viewer, ignoring any
   *                 catalog. Useful for verifying the fallback on demand.
   */
  /* LIVE ONLY. [Joshua, 2 Oct 2026: "No more placeholder data please it
   * should be live".] Placeholder ("seed") data is never shown to the public:
   * catalog.js refuses it outside the test harness, and seed/ does not ship.
   * Served by the studio server, the live URLs below are replaced with the
   * Mac mini's own; served from Vercel they read Supabase (real data). */
  catalogSource: 'live',

  /* Kat's Supabase project hnwyoglbmhvafxnzizqe since 3 Oct 2026 (db/kat-project/).
   *
   * The publishable key below is meant to be public — it is in the page source
   * of every kiosk. What keeps the catalog safe is row-level security in the
   * database, not secrecy of this key: the public role can SELECT live content
   * and nothing else. No inserts, no updates, no deletes, and drafts stay
   * invisible. Dashboard writes will authenticate separately.
   *
   * The tables are EMPTY. Until real content is imported, catalogSource stays
   * on 'seed'. */
  live: {
    url: 'https://hnwyoglbmhvafxnzizqe.supabase.co/rest/v1/kiosk_catalog?select=*',
    anonKey: 'sb_publishable_XWA6QYk4ukTcmqvqjnBniw_DfvzQsZh',
    /* Columns are listed explicitly and MUST stay that way. The public role no
     * longer has SELECT on the whole artists row — email, role and
     * auth_user_id are revoked from it, because this key is in the kiosk's
     * page source and artist emails are not public information. A bare
     * `select=*` here now returns 42501 permission denied.
     *
     * The flip side of that, and the reason this comment is longer than it
     * looks like it needs to be: a NEW column is invisible to the kiosk until
     * somebody adds it to this list. portrait_thumb_url is the 256px headshot
     * the dashboard generates, and if it is missing here the kiosk silently
     * falls back to the 1024px original — which works, and is 16x the bytes,
     * and nothing anywhere reports it. */
    artistsUrl: 'https://hnwyoglbmhvafxnzizqe.supabase.co/rest/v1/artists'
      + '?active=eq.true&order=display_order'
      + '&select=id,name,handle,portrait_url,portrait_thumb_url,bio,instagram_url,seniority,display_order',
    categoriesUrl: 'https://hnwyoglbmhvafxnzizqe.supabase.co/rest/v1/categories?order=display_order',
    // Kiosk re-fetches on this interval. On failure the last good catalog is
    // kept and reused — a dropped network mid-shift must never blank the
    // screen (PRD §4.2).
    refreshMs: 5 * 60 * 1000,
  },

  /* Destination for the QR badge in the sheet viewer when no artist is in
   * scope. Defaults to the online gallery so a customer scanning it lands on
   * the flash they are looking at. Not confirmed by Joshua — change freely. */
  galleryUrl: 'https://kattitude-flash-kiosk.vercel.app',   // Kat's Vercel (kattitudekiosk) since 3 Oct 2026

  /* Sheets always come from data.js — they are real content that exists
   * today and predates the catalog. Set false only if sheets should stop
   * appearing entirely. */
  includeSheets: true,

  /* Zoom. [Joshua, 2 Oct 2026: "I don't really want the customer to be able
   * to zoom in on the sheets ... I don't really want the zoom function".]
   * false: sheets show fitted to the screen with no tap/pinch/wheel zoom, and
   * single designs open in a lightbox — larger, fitted, tap anywhere on the
   * picture (or Back) to close. true restores the old zoom on both. */
  zoom: false,

  /* When the catalog has zero individual designs AND no artists, the kiosk
   * routes straight into the legacy linear sheet viewer. With artists on the
   * roster it shows the home screen instead, so Browse by Artist and the
   * headshots are reachable before anybody has uploaded a design (changed
   * 2 Oct 2026, CLAUDE.md invariant 4). Leave true. */
  sheetsOnlyFallback: true,

  /* Home screen is skipped when there is only one artist AND no sheets —
   * a hub with a single destination is a wasted tap. */
  skipHomeWhenSingleArtist: true,

  /* Visible banner marking placeholder content. Auto-on for seed, and worth
   * leaving on until real content lands. */
  showSeedBanner: false,   // retired: there is no placeholder data to label

  /* "Full Flash Sheets" on the cover — decided 9 Oct 2026, Joshua: "i feel
   * like the full flash sheets tab is redundant. Let's go with the browse by
   * all and then the artists tab only". Sheets stay in View All (as tiles that
   * open the sheet viewer) and on every artist's page. */
  coverSheetsCard: false,

  /* Show "Studio Owner" / "Senior Artist" / "Junior Artist" on artist cards.
   * Off by default: the data is real and useful for ordering, but labelling
   * artists as junior to a walk-in customer is the studio's call, not a
   * layout default. Flip to true if Joshua wants it visible. */
  showSeniority: false,

  grid: {
    columns: 3,          // 1080px wide → 360px tiles (PRD §3.2)
    defaultSort: 'newest', // 'newest' | 'artist' | 'category'
  },

  /* ── Attract loop ──────────────────────────────────────────────────
   * One reel of video clips and flash stills woven together, NOT two modes
   * that alternate. With zero clips this whole subsystem stands down and
   * script.js runs its original sheet cycle — the thing on the wall today —
   * unchanged.
   *
   * WHERE THE VIDEO LIVES: on the Mac mini's own disk. Clips are pulled from
   * Supabase ONCE into Cache Storage, which is persistent local disk for the
   * origin, then played from an in-memory blob forever after. Egress is one
   * download per clip for the life of the machine, not per loop and not per
   * day, and the loop keeps running if the shop's internet drops. No local
   * web server to babysit and nobody has to be at the shop — which matters,
   * because nobody is.
   */
  screensaver: {
    /* Which flash appears between clips.
     *   'all'      — sheets and published designs
     *   'sheets'   — sheets only
     *   'featured' — featured items only
     * The studio has 4 sheets and no singles today, so all three currently
     * resolve to the same 4 sheets. */
    source: 'all',

    /* One clip, then this many stills, then the next clip. Raise it to make
     * video an occasional punctuation; lower it for a video-led reel. */
    stillsPerClip: 4,

    stillMs: 8000,      // matches the existing sheet cadence exactly
    maxClipMs: 45000,   // a stalled or over-long clip can't own the screen
    fadeMs: 600,        // crossfade; the outgoing frame is never torn down first

    /* Manifest of clips. Normally fetched from Supabase and cached locally;
     * this list is the offline/no-backend fallback and is empty on purpose.
     * Adding a clip here is also the quickest way to test one. */
    clips: [],
    clipsUrl: null,     // e.g. the screensaver_clips REST endpoint
  },

  /* Return to home after inactivity (PRD §4.3). The legacy screensaver in
   * script.js has its own longer idle timer for the attract loop; this is the
   * shorter "next customer starts clean" reset. */
  idleResetMs: 90 * 1000,
};
