-- 05 — TEMPORARY. Lets the publishable (anon) key INSERT exactly these
-- 12 objects, so the studio's files can be uploaded with no service key.
-- Generated by storage-upload.js --sql from the studio database. Insert only:
-- no overwrite, no delete, no other name. Run 06 straight after the upload.
create policy kt_migration_upload on storage.objects for insert to anon
  with check ((bucket_id, name) in (values
    ('flash', '14045c7d-df79-4361-b5e0-3b1c820990dc/_kiosk/IMG_2120/kiosk.jpg'),
    ('flash', '14045c7d-df79-4361-b5e0-3b1c820990dc/_kiosk/Untitled_Artwork/kiosk.jpg'),
    ('flash', 'e69eecbc-ae36-447b-b924-a64e201eef6b/_kiosk/IMG_1705/kiosk.jpg'),
    ('flash', 'ad5ed37b-ea72-4172-8362-e6d8623c82b1/_kiosk/Untitled_Artwork_2_web/kiosk.jpg'),
    ('flash', '14045c7d-df79-4361-b5e0-3b1c820990dc/_kiosk/IMG_2120/thumb.jpg'),
    ('flash', '14045c7d-df79-4361-b5e0-3b1c820990dc/_kiosk/Untitled_Artwork/thumb.jpg'),
    ('flash', 'e69eecbc-ae36-447b-b924-a64e201eef6b/_kiosk/IMG_1705/thumb.jpg'),
    ('flash', 'ad5ed37b-ea72-4172-8362-e6d8623c82b1/_kiosk/Untitled_Artwork_2_web/thumb.jpg'),
    ('avatars', '9e767f86-c114-47b4-b7e4-78f780bbdc4f/avatar-msxrpxsk.webp'),
    ('avatars', '5f7e39b9-20a2-4101-8da5-83476636edc3/avatar-msnts7xa.webp'),
    ('avatars', '9e767f86-c114-47b4-b7e4-78f780bbdc4f/avatar-msxrpxsk-sm.webp'),
    ('avatars', '5f7e39b9-20a2-4101-8da5-83476636edc3/avatar-msnts7xa-sm.webp')
  ));
select count(*) as allowed_objects from (values
    ('flash', '14045c7d-df79-4361-b5e0-3b1c820990dc/_kiosk/IMG_2120/kiosk.jpg'),
    ('flash', '14045c7d-df79-4361-b5e0-3b1c820990dc/_kiosk/Untitled_Artwork/kiosk.jpg'),
    ('flash', 'e69eecbc-ae36-447b-b924-a64e201eef6b/_kiosk/IMG_1705/kiosk.jpg'),
    ('flash', 'ad5ed37b-ea72-4172-8362-e6d8623c82b1/_kiosk/Untitled_Artwork_2_web/kiosk.jpg'),
    ('flash', '14045c7d-df79-4361-b5e0-3b1c820990dc/_kiosk/IMG_2120/thumb.jpg'),
    ('flash', '14045c7d-df79-4361-b5e0-3b1c820990dc/_kiosk/Untitled_Artwork/thumb.jpg'),
    ('flash', 'e69eecbc-ae36-447b-b924-a64e201eef6b/_kiosk/IMG_1705/thumb.jpg'),
    ('flash', 'ad5ed37b-ea72-4172-8362-e6d8623c82b1/_kiosk/Untitled_Artwork_2_web/thumb.jpg'),
    ('avatars', '9e767f86-c114-47b4-b7e4-78f780bbdc4f/avatar-msxrpxsk.webp'),
    ('avatars', '5f7e39b9-20a2-4101-8da5-83476636edc3/avatar-msnts7xa.webp'),
    ('avatars', '9e767f86-c114-47b4-b7e4-78f780bbdc4f/avatar-msxrpxsk-sm.webp'),
    ('avatars', '5f7e39b9-20a2-4101-8da5-83476636edc3/avatar-msnts7xa-sm.webp')
) v;
