/* db/kat-project/storage-upload.js — move the studio's files into Kat's
 * Supabase storage WITHOUT a service-role key.
 *
 * The files are the ones the studio database points at: each design's kiosk
 * image and thumbnail, and each headshot and its small copy — read from
 * ~/Desktop/KIOSK MEDIA, where the studio server keeps them. KIOSK MEDIA's
 * placeholder/ folder is never read, because no database row points into it.
 *
 *   node db/kat-project/storage-upload.js --sql
 *       writes 05-upload-open.sql: a temporary policy letting the PUBLIC key
 *       insert exactly these object names and nothing else (no overwrite,
 *       no other name, no other bucket), and 06-upload-close.sql to drop it.
 *
 *   node db/kat-project/storage-upload.js --upload <publishable key>
 *       uploads each file, then downloads it back from its public URL and
 *       compares sha256 with the file on disk. Run between 05 and 06.
 *
 * The publishable key is public by design (it ships in the kiosk's page
 * source). It is passed on the command line, never written to a file.
 */
'use strict';

const fs = require('fs');
const os = require('os');
const path = require('path');
const crypto = require('crypto');
const { DatabaseSync } = require('node:sqlite');

const HOST = 'https://hnwyoglbmhvafxnzizqe.supabase.co';
const DB = process.env.KATTITUDE_DB || path.join(os.homedir(), 'KattitudeData', 'kattitude.db');
const MEDIA = process.env.KIOSK_MEDIA || path.join(os.homedir(), 'Desktop', 'KIOSK MEDIA');
const PREFIX = '/storage/v1/object/public/';
const TYPES = { '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.png': 'image/png', '.webp': 'image/webp' };

setTimeout(() => { console.error('storage-upload.js: timed out'); process.exit(2); }, 300000).unref();

/* Every file the database points at, mapped to where it sits on disk.
 * flash/<artist_id>/<rest>   -> KIOSK MEDIA/<Artist>/Designs/<rest>
 * avatars/<artist_id>/<file> -> KIOSK MEDIA/<Artist>/Headshots/<file> */
function objects() {
  const db = new DatabaseSync(DB, { readOnly: true });
  const names = Object.fromEntries(db.prepare('select id, name from artists').all().map(a => [a.id, a.name]));
  const urls = [
    ...db.prepare('select image_url u from designs union all select thumb_url from designs').all(),
    ...db.prepare('select portrait_url u from artists union all select portrait_thumb_url from artists').all(),
  ].map(r => r.u).filter(Boolean);
  db.close();
  return urls.map(u => {
    if (!u.startsWith(PREFIX)) throw new Error('not a studio storage path: ' + u);
    const [bucket, artistId, ...rest] = u.slice(PREFIX.length).split('/');
    const folder = { flash: 'Designs', avatars: 'Headshots' }[bucket];
    if (!folder || !names[artistId]) throw new Error('cannot map ' + u);
    const file = path.join(MEDIA, names[artistId], folder, ...rest);
    if (file.includes(`${path.sep}placeholder${path.sep}`)) throw new Error('placeholder file: ' + file);
    if (!fs.existsSync(file)) throw new Error('missing on disk: ' + file);
    return { bucket, name: [artistId, ...rest].join('/'), file };
  });
}

function sql(list) {
  const q = s => `'${s.replace(/'/g, "''")}'`;
  const pairs = list.map(o => `    (${q(o.bucket)}, ${q(o.name)})`).join(',\n');
  fs.writeFileSync(path.join(__dirname, '05-upload-open.sql'),
`-- 05 — TEMPORARY. Lets the publishable (anon) key INSERT exactly these
-- ${list.length} objects, so the studio's files can be uploaded with no service key.
-- Generated by storage-upload.js --sql from the studio database. Insert only:
-- no overwrite, no delete, no other name. Run 06 straight after the upload.
create policy kt_migration_upload on storage.objects for insert to anon
  with check ((bucket_id, name) in (values
${pairs}
  ));
select count(*) as allowed_objects from (values
${pairs}
) v;
`);
  fs.writeFileSync(path.join(__dirname, '06-upload-close.sql'),
`-- 06 — Closes the window 05 opened, then proves it is closed and that every
-- file arrived. Run straight after storage-upload.js --upload.
drop policy if exists kt_migration_upload on storage.objects;

select 'temporary policy gone' as check_name,
       (select count(*) from pg_policies where policyname = 'kt_migration_upload') = 0 as pass
union all
select 'all ${list.length} objects stored',
       (select count(*) from storage.objects o
         where (o.bucket_id, o.name) in (values
${pairs.replace(/^ {4}/gm, '           ')}
         )) = ${list.length};
`);
  console.log(`wrote 05-upload-open.sql and 06-upload-close.sql for ${list.length} objects`);
}

async function upload(list, key) {
  if (!key || !/^sb_publishable_|^eyJ/.test(key)) throw new Error('pass the project\'s publishable key');
  if (/^sb_secret_/.test(key)) throw new Error('that is a SECRET key — never use it here');
  let bad = 0;
  for (const o of list) {
    const body = fs.readFileSync(o.file);
    const sum = crypto.createHash('sha256').update(body).digest('hex');
    const up = await fetch(`${HOST}/storage/v1/object/${o.bucket}/${o.name}`, {
      method: 'POST',
      headers: { apikey: key, Authorization: `Bearer ${key}`, 'x-upsert': 'false',
                 'Content-Type': TYPES[path.extname(o.file).toLowerCase()] || 'application/octet-stream',
                 'Cache-Control': 'max-age=31536000' },
      body,
    });
    const back = await fetch(`${HOST}${PREFIX}${o.bucket}/${o.name}`);
    const got = back.ok ? crypto.createHash('sha256').update(Buffer.from(await back.arrayBuffer())).digest('hex') : null;
    const ok = got === sum;
    if (!ok) bad++;
    console.log(`  ${ok ? 'ok  ' : 'FAIL'} ${o.bucket}/${o.name}  upload ${up.status}  ` +
      `public GET ${back.status}  ${ok ? 'sha256 matches' : 'sha256 ' + (got ? 'DIFFERS' : 'n/a') + (up.ok ? '' : ' — ' + (await up.text()).slice(0, 120))}`);
  }
  console.log(`\n${list.length - bad}/${list.length} files stored byte-for-byte`);
  return bad;
}

(async () => {
  const list = objects();
  if (process.argv.includes('--sql')) return sql(list);
  const i = process.argv.indexOf('--upload');
  if (i !== -1) process.exit(await upload(list, process.argv[i + 1]) ? 1 : 0);
  list.forEach(o => console.log(`${o.bucket}/${o.name}  <-  ${o.file}`));
})().then(() => process.exit(0), e => { console.error(e.message); process.exit(1); });
